/*
 * attachmentAV
 * An SDK to integrate virus and malware scan capabilities into Java applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.api;

import com.attachmentav.client.ApiException;
import com.attachmentav.model.AsyncDownloadScanRequest;
import com.attachmentav.model.AsyncS3ScanRequest;
import java.io.File;
import com.attachmentav.model.ScanResult;
import com.attachmentav.model.SyncDownloadScanRequest;
import com.attachmentav.model.SyncS3ScanRequest;
import com.attachmentav.model.Usage;
import com.attachmentav.model.Whoami;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AttachmentAvApi
 */
@Disabled
public class AttachmentAvApiTest {

    private final AttachmentAvApi api = new AttachmentAvApi();

    /**
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and post the scan result to your callback URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanAsyncDownloadPostTest() throws ApiException {
        AsyncDownloadScanRequest asyncDownloadScanRequest = null;
        api.scanAsyncDownloadPost(asyncDownloadScanRequest);
        // TODO: test validations
    }

    /**
     * Retrieve the scan result for scan job.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanAsyncResultGetTest() throws ApiException {
        String traceId = null;
        ScanResult response = api.scanAsyncResultGet(traceId);
        // TODO: test validations
    }

    /**
     * Download a file from S3, scan the file, and post the scan result to your callback URL. A bucket policy is required to grant attachmentAV access to the S3 objects.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanAsyncS3PostTest() throws ApiException {
        AsyncS3ScanRequest asyncS3ScanRequest = null;
        api.scanAsyncS3Post(asyncS3ScanRequest);
        // TODO: test validations
    }

    /**
     * Upload a file, scan the file, and return the scan result.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncBinaryPostTest() throws ApiException {
        File body = null;
        ScanResult response = api.scanSyncBinaryPost(body);
        // TODO: test validations
    }

    /**
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and return the scan result.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncDownloadPostTest() throws ApiException {
        SyncDownloadScanRequest syncDownloadScanRequest = null;
        ScanResult response = api.scanSyncDownloadPost(syncDownloadScanRequest);
        // TODO: test validations
    }

    /**
     * Download a file from S3, scan the file, and return the scan result. A bucket policy is required to grant attachmentAV access to the S3 objects.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncS3PostTest() throws ApiException {
        SyncS3ScanRequest syncS3ScanRequest = null;
        ScanResult response = api.scanSyncS3Post(syncS3ScanRequest);
        // TODO: test validations
    }

    /**
     * Get remaining credits and quota.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usageGetTest() throws ApiException {
        Usage response = api.usageGet();
        // TODO: test validations
    }

    /**
     * Get information abour yourself.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void whoamiGetTest() throws ApiException {
        Whoami response = api.whoamiGet();
        // TODO: test validations
    }

}
