/*
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.api;

import com.attachmentav.client.ApiException;
import java.io.File;
import com.attachmentav.model.ScanResult;
import com.attachmentav.model.SyncDownloadScanRequest;
import com.attachmentav.model.SyncS3ScanRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AttachmentAvApi
 */
@Disabled
public class AttachmentAvApiTest {

    private final AttachmentAvApi api = new AttachmentAvApi();

    /**
     * Upload a file, scan the file, and return the scan result.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncBinaryPostTest() throws ApiException {
        File body = null;
        ScanResult response = api.scanSyncBinaryPost(body);
        // TODO: test validations
    }

    /**
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and return the scan result.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncDownloadPostTest() throws ApiException {
        SyncDownloadScanRequest syncDownloadScanRequest = null;
        ScanResult response = api.scanSyncDownloadPost(syncDownloadScanRequest);
        // TODO: test validations
    }

    /**
     * Upload a file, scan the file, and return the scan result.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncFormPostTest() throws ApiException {
        File _file = null;
        ScanResult response = api.scanSyncFormPost(_file);
        // TODO: test validations
    }

    /**
     * Download a file from S3, scan the file, and return the scan result. A bucket policy is required to grant attachmentAV access to the S3 objects.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void scanSyncS3PostTest() throws ApiException {
        SyncS3ScanRequest syncS3ScanRequest = null;
        ScanResult response = api.scanSyncS3Post(syncS3ScanRequest);
        // TODO: test validations
    }

}
