/*
 * attachmentAV
 * An SDK to integrate virus and malware scan capabilities into Java applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.model;

import java.util.Objects;
import com.attachmentav.model.CallbackFailure;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.attachmentav.client.JSON;

/**
 * CallbackFailures
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-13T21:53:27.254284+02:00[Europe/Berlin]", comments = "Generator version: 7.23.0")
public class CallbackFailures {
  public static final String SERIALIZED_NAME_FAILURES = "failures";
  @SerializedName(SERIALIZED_NAME_FAILURES)
  @javax.annotation.Nonnull
  private List<CallbackFailure> failures = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEXT_CURSOR = "next_cursor";
  @SerializedName(SERIALIZED_NAME_NEXT_CURSOR)
  @javax.annotation.Nullable
  private String nextCursor;

  public CallbackFailures() {
  }

  public CallbackFailures failures(@javax.annotation.Nonnull List<CallbackFailure> failures) {
    this.failures = failures;
    return this;
  }

  public CallbackFailures addFailuresItem(CallbackFailure failuresItem) {
    if (this.failures == null) {
      this.failures = new ArrayList<>();
    }
    this.failures.add(failuresItem);
    return this;
  }

  /**
   * Get failures
   * @return failures
   */
  @javax.annotation.Nonnull
  public List<CallbackFailure> getFailures() {
    return failures;
  }

  public void setFailures(@javax.annotation.Nonnull List<CallbackFailure> failures) {
    this.failures = failures;
  }


  public CallbackFailures nextCursor(@javax.annotation.Nullable String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * Get nextCursor
   * @return nextCursor
   */
  @javax.annotation.Nullable
  public String getNextCursor() {
    return nextCursor;
  }

  public void setNextCursor(@javax.annotation.Nullable String nextCursor) {
    this.nextCursor = nextCursor;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallbackFailures callbackFailures = (CallbackFailures) o;
    return Objects.equals(this.failures, callbackFailures.failures) &&
        Objects.equals(this.nextCursor, callbackFailures.nextCursor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failures, nextCursor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallbackFailures {\n");
    sb.append("    failures: ").append(toIndentedString(failures)).append("\n");
    sb.append("    nextCursor: ").append(toIndentedString(nextCursor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("failures", "next_cursor"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("failures"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CallbackFailures
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CallbackFailures.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CallbackFailures is not found in the empty JSON string", CallbackFailures.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CallbackFailures.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CallbackFailures` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CallbackFailures.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("failures") != null) {
        if (!jsonObj.get("failures").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `failures` to be an array in the JSON string but got `%s`", jsonObj.get("failures").toString()));
        }
        JsonArray jsonArrayfailures = jsonObj.getAsJsonArray("failures");
        // validate the required field `failures` (array)
        for (int i = 0; i < jsonArrayfailures.size(); i++) {
          CallbackFailure.validateJsonElement(jsonArrayfailures.get(i));
        }
      }
      if ((jsonObj.get("next_cursor") != null && !jsonObj.get("next_cursor").isJsonNull()) && !jsonObj.get("next_cursor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `next_cursor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("next_cursor").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CallbackFailures.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CallbackFailures' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CallbackFailures> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CallbackFailures.class));

       return (TypeAdapter<T>) new TypeAdapter<CallbackFailures>() {
           @Override
           public void write(JsonWriter out, CallbackFailures value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CallbackFailures read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CallbackFailures given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CallbackFailures
   * @throws IOException if the JSON string is invalid with respect to CallbackFailures
   */
  public static CallbackFailures fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CallbackFailures.class);
  }

  /**
   * Convert an instance of CallbackFailures to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

