/*
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.attachmentav.client.JSON;

/**
 * ScanResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-15T09:36:10.987866+02:00[Europe/Berlin]", comments = "Generator version: 7.14.0")
public class ScanResult {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_FINDING = "finding";
  @SerializedName(SERIALIZED_NAME_FINDING)
  @javax.annotation.Nullable
  private String finding;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nullable
  private String size;

  public static final String SERIALIZED_NAME_REALFILETYPE = "realfiletype";
  @SerializedName(SERIALIZED_NAME_REALFILETYPE)
  @javax.annotation.Nullable
  private String realfiletype;

  public ScanResult() {
  }

  public ScanResult status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ScanResult finding(@javax.annotation.Nullable String finding) {
    this.finding = finding;
    return this;
  }

  /**
   * Get finding
   * @return finding
   */
  @javax.annotation.Nullable
  public String getFinding() {
    return finding;
  }

  public void setFinding(@javax.annotation.Nullable String finding) {
    this.finding = finding;
  }


  public ScanResult size(@javax.annotation.Nullable String size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   */
  @javax.annotation.Nullable
  public String getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nullable String size) {
    this.size = size;
  }


  public ScanResult realfiletype(@javax.annotation.Nullable String realfiletype) {
    this.realfiletype = realfiletype;
    return this;
  }

  /**
   * Get realfiletype
   * @return realfiletype
   */
  @javax.annotation.Nullable
  public String getRealfiletype() {
    return realfiletype;
  }

  public void setRealfiletype(@javax.annotation.Nullable String realfiletype) {
    this.realfiletype = realfiletype;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScanResult scanResult = (ScanResult) o;
    return Objects.equals(this.status, scanResult.status) &&
        Objects.equals(this.finding, scanResult.finding) &&
        Objects.equals(this.size, scanResult.size) &&
        Objects.equals(this.realfiletype, scanResult.realfiletype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, finding, size, realfiletype);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScanResult {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    finding: ").append(toIndentedString(finding)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    realfiletype: ").append(toIndentedString(realfiletype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("status", "finding", "size", "realfiletype"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScanResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScanResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScanResult is not found in the empty JSON string", ScanResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScanResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScanResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("finding") != null && !jsonObj.get("finding").isJsonNull()) && !jsonObj.get("finding").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `finding` to be a primitive type in the JSON string but got `%s`", jsonObj.get("finding").toString()));
      }
      if ((jsonObj.get("size") != null && !jsonObj.get("size").isJsonNull()) && !jsonObj.get("size").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `size` to be a primitive type in the JSON string but got `%s`", jsonObj.get("size").toString()));
      }
      if ((jsonObj.get("realfiletype") != null && !jsonObj.get("realfiletype").isJsonNull()) && !jsonObj.get("realfiletype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `realfiletype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("realfiletype").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScanResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScanResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScanResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScanResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ScanResult>() {
           @Override
           public void write(JsonWriter out, ScanResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScanResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScanResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScanResult
   * @throws IOException if the JSON string is invalid with respect to ScanResult
   */
  public static ScanResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScanResult.class);
  }

  /**
   * Convert an instance of ScanResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

