/*
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.attachmentav.client.JSON;

/**
 * SyncDownloadScanRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-16T09:59:54.016330+02:00[Europe/Berlin]", comments = "Generator version: 7.14.0")
public class SyncDownloadScanRequest {
  public static final String SERIALIZED_NAME_DOWNLOAD_URL = "download_url";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_URL)
  @javax.annotation.Nonnull
  private String downloadUrl;

  public static final String SERIALIZED_NAME_DOWNLOAD_HEADERS = "download_headers";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_HEADERS)
  @javax.annotation.Nullable
  private Map<String, String> downloadHeaders = new HashMap<>();

  public SyncDownloadScanRequest() {
  }

  public SyncDownloadScanRequest downloadUrl(@javax.annotation.Nonnull String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

  /**
   * Get downloadUrl
   * @return downloadUrl
   */
  @javax.annotation.Nonnull
  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(@javax.annotation.Nonnull String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }


  public SyncDownloadScanRequest downloadHeaders(@javax.annotation.Nullable Map<String, String> downloadHeaders) {
    this.downloadHeaders = downloadHeaders;
    return this;
  }

  public SyncDownloadScanRequest putDownloadHeadersItem(String key, String downloadHeadersItem) {
    if (this.downloadHeaders == null) {
      this.downloadHeaders = new HashMap<>();
    }
    this.downloadHeaders.put(key, downloadHeadersItem);
    return this;
  }

  /**
   * Get downloadHeaders
   * @return downloadHeaders
   */
  @javax.annotation.Nullable
  public Map<String, String> getDownloadHeaders() {
    return downloadHeaders;
  }

  public void setDownloadHeaders(@javax.annotation.Nullable Map<String, String> downloadHeaders) {
    this.downloadHeaders = downloadHeaders;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncDownloadScanRequest syncDownloadScanRequest = (SyncDownloadScanRequest) o;
    return Objects.equals(this.downloadUrl, syncDownloadScanRequest.downloadUrl) &&
        Objects.equals(this.downloadHeaders, syncDownloadScanRequest.downloadHeaders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadUrl, downloadHeaders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncDownloadScanRequest {\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    downloadHeaders: ").append(toIndentedString(downloadHeaders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("download_url", "download_headers"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("download_url"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SyncDownloadScanRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SyncDownloadScanRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SyncDownloadScanRequest is not found in the empty JSON string", SyncDownloadScanRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SyncDownloadScanRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SyncDownloadScanRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SyncDownloadScanRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("download_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `download_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("download_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SyncDownloadScanRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SyncDownloadScanRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SyncDownloadScanRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SyncDownloadScanRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SyncDownloadScanRequest>() {
           @Override
           public void write(JsonWriter out, SyncDownloadScanRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SyncDownloadScanRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SyncDownloadScanRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SyncDownloadScanRequest
   * @throws IOException if the JSON string is invalid with respect to SyncDownloadScanRequest
   */
  public static SyncDownloadScanRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SyncDownloadScanRequest.class);
  }

  /**
   * Convert an instance of SyncDownloadScanRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

