/*
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.api;

import com.attachmentav.client.ApiCallback;
import com.attachmentav.client.ApiClient;
import com.attachmentav.client.ApiException;
import com.attachmentav.client.ApiResponse;
import com.attachmentav.client.Configuration;
import com.attachmentav.client.Pair;
import com.attachmentav.client.ProgressRequestBody;
import com.attachmentav.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.attachmentav.model.AsyncDownloadScanRequest;
import com.attachmentav.model.AsyncS3ScanRequest;
import java.io.File;
import com.attachmentav.model.ScanResult;
import com.attachmentav.model.SyncDownloadScanRequest;
import com.attachmentav.model.SyncS3ScanRequest;
import com.attachmentav.model.Whoami;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AttachmentAvApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AttachmentAvApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AttachmentAvApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for scanAsyncDownloadPost
     * @param asyncDownloadScanRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanAsyncDownloadPostCall(@javax.annotation.Nonnull AsyncDownloadScanRequest asyncDownloadScanRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncDownloadScanRequest;

        // create path and map variables
        String localVarPath = "/scan/async/download";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKeyAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call scanAsyncDownloadPostValidateBeforeCall(@javax.annotation.Nonnull AsyncDownloadScanRequest asyncDownloadScanRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncDownloadScanRequest' is set
        if (asyncDownloadScanRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncDownloadScanRequest' when calling scanAsyncDownloadPost(Async)");
        }

        return scanAsyncDownloadPostCall(asyncDownloadScanRequest, _callback);

    }

    /**
     * 
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and post the scan result to your callback URL.
     * @param asyncDownloadScanRequest  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public void scanAsyncDownloadPost(@javax.annotation.Nonnull AsyncDownloadScanRequest asyncDownloadScanRequest) throws ApiException {
        scanAsyncDownloadPostWithHttpInfo(asyncDownloadScanRequest);
    }

    /**
     * 
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and post the scan result to your callback URL.
     * @param asyncDownloadScanRequest  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> scanAsyncDownloadPostWithHttpInfo(@javax.annotation.Nonnull AsyncDownloadScanRequest asyncDownloadScanRequest) throws ApiException {
        okhttp3.Call localVarCall = scanAsyncDownloadPostValidateBeforeCall(asyncDownloadScanRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     *  (asynchronously)
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and post the scan result to your callback URL.
     * @param asyncDownloadScanRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanAsyncDownloadPostAsync(@javax.annotation.Nonnull AsyncDownloadScanRequest asyncDownloadScanRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = scanAsyncDownloadPostValidateBeforeCall(asyncDownloadScanRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for scanAsyncS3Post
     * @param asyncS3ScanRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanAsyncS3PostCall(@javax.annotation.Nonnull AsyncS3ScanRequest asyncS3ScanRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = asyncS3ScanRequest;

        // create path and map variables
        String localVarPath = "/scan/async/s3";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKeyAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call scanAsyncS3PostValidateBeforeCall(@javax.annotation.Nonnull AsyncS3ScanRequest asyncS3ScanRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'asyncS3ScanRequest' is set
        if (asyncS3ScanRequest == null) {
            throw new ApiException("Missing the required parameter 'asyncS3ScanRequest' when calling scanAsyncS3Post(Async)");
        }

        return scanAsyncS3PostCall(asyncS3ScanRequest, _callback);

    }

    /**
     * 
     * Download a file from S3, scan the file, and post the scan result to your callback URL. A bucket policy is required to grant attachmentAV access to the S3 objects.
     * @param asyncS3ScanRequest  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public void scanAsyncS3Post(@javax.annotation.Nonnull AsyncS3ScanRequest asyncS3ScanRequest) throws ApiException {
        scanAsyncS3PostWithHttpInfo(asyncS3ScanRequest);
    }

    /**
     * 
     * Download a file from S3, scan the file, and post the scan result to your callback URL. A bucket policy is required to grant attachmentAV access to the S3 objects.
     * @param asyncS3ScanRequest  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> scanAsyncS3PostWithHttpInfo(@javax.annotation.Nonnull AsyncS3ScanRequest asyncS3ScanRequest) throws ApiException {
        okhttp3.Call localVarCall = scanAsyncS3PostValidateBeforeCall(asyncS3ScanRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     *  (asynchronously)
     * Download a file from S3, scan the file, and post the scan result to your callback URL. A bucket policy is required to grant attachmentAV access to the S3 objects.
     * @param asyncS3ScanRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanAsyncS3PostAsync(@javax.annotation.Nonnull AsyncS3ScanRequest asyncS3ScanRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = scanAsyncS3PostValidateBeforeCall(asyncS3ScanRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for scanSyncBinaryPost
     * @param body  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanSyncBinaryPostCall(@javax.annotation.Nonnull File body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/scan/sync/binary";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKeyAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call scanSyncBinaryPostValidateBeforeCall(@javax.annotation.Nonnull File body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling scanSyncBinaryPost(Async)");
        }

        return scanSyncBinaryPostCall(body, _callback);

    }

    /**
     * 
     * Upload a file, scan the file, and return the scan result.
     * @param body  (required)
     * @return ScanResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ScanResult scanSyncBinaryPost(@javax.annotation.Nonnull File body) throws ApiException {
        ApiResponse<ScanResult> localVarResp = scanSyncBinaryPostWithHttpInfo(body);
        return localVarResp.getData();
    }

    /**
     * 
     * Upload a file, scan the file, and return the scan result.
     * @param body  (required)
     * @return ApiResponse&lt;ScanResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ScanResult> scanSyncBinaryPostWithHttpInfo(@javax.annotation.Nonnull File body) throws ApiException {
        okhttp3.Call localVarCall = scanSyncBinaryPostValidateBeforeCall(body, null);
        Type localVarReturnType = new TypeToken<ScanResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Upload a file, scan the file, and return the scan result.
     * @param body  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanSyncBinaryPostAsync(@javax.annotation.Nonnull File body, final ApiCallback<ScanResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = scanSyncBinaryPostValidateBeforeCall(body, _callback);
        Type localVarReturnType = new TypeToken<ScanResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for scanSyncDownloadPost
     * @param syncDownloadScanRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanSyncDownloadPostCall(@javax.annotation.Nonnull SyncDownloadScanRequest syncDownloadScanRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = syncDownloadScanRequest;

        // create path and map variables
        String localVarPath = "/scan/sync/download";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKeyAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call scanSyncDownloadPostValidateBeforeCall(@javax.annotation.Nonnull SyncDownloadScanRequest syncDownloadScanRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'syncDownloadScanRequest' is set
        if (syncDownloadScanRequest == null) {
            throw new ApiException("Missing the required parameter 'syncDownloadScanRequest' when calling scanSyncDownloadPost(Async)");
        }

        return scanSyncDownloadPostCall(syncDownloadScanRequest, _callback);

    }

    /**
     * 
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and return the scan result.
     * @param syncDownloadScanRequest  (required)
     * @return ScanResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ScanResult scanSyncDownloadPost(@javax.annotation.Nonnull SyncDownloadScanRequest syncDownloadScanRequest) throws ApiException {
        ApiResponse<ScanResult> localVarResp = scanSyncDownloadPostWithHttpInfo(syncDownloadScanRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and return the scan result.
     * @param syncDownloadScanRequest  (required)
     * @return ApiResponse&lt;ScanResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ScanResult> scanSyncDownloadPostWithHttpInfo(@javax.annotation.Nonnull SyncDownloadScanRequest syncDownloadScanRequest) throws ApiException {
        okhttp3.Call localVarCall = scanSyncDownloadPostValidateBeforeCall(syncDownloadScanRequest, null);
        Type localVarReturnType = new TypeToken<ScanResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Download a file from a remote location (HTTP/HTTPS), scan the file, and return the scan result.
     * @param syncDownloadScanRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanSyncDownloadPostAsync(@javax.annotation.Nonnull SyncDownloadScanRequest syncDownloadScanRequest, final ApiCallback<ScanResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = scanSyncDownloadPostValidateBeforeCall(syncDownloadScanRequest, _callback);
        Type localVarReturnType = new TypeToken<ScanResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for scanSyncS3Post
     * @param syncS3ScanRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanSyncS3PostCall(@javax.annotation.Nonnull SyncS3ScanRequest syncS3ScanRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = syncS3ScanRequest;

        // create path and map variables
        String localVarPath = "/scan/sync/s3";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKeyAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call scanSyncS3PostValidateBeforeCall(@javax.annotation.Nonnull SyncS3ScanRequest syncS3ScanRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'syncS3ScanRequest' is set
        if (syncS3ScanRequest == null) {
            throw new ApiException("Missing the required parameter 'syncS3ScanRequest' when calling scanSyncS3Post(Async)");
        }

        return scanSyncS3PostCall(syncS3ScanRequest, _callback);

    }

    /**
     * 
     * Download a file from S3, scan the file, and return the scan result. A bucket policy is required to grant attachmentAV access to the S3 objects.
     * @param syncS3ScanRequest  (required)
     * @return ScanResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ScanResult scanSyncS3Post(@javax.annotation.Nonnull SyncS3ScanRequest syncS3ScanRequest) throws ApiException {
        ApiResponse<ScanResult> localVarResp = scanSyncS3PostWithHttpInfo(syncS3ScanRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Download a file from S3, scan the file, and return the scan result. A bucket policy is required to grant attachmentAV access to the S3 objects.
     * @param syncS3ScanRequest  (required)
     * @return ApiResponse&lt;ScanResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ScanResult> scanSyncS3PostWithHttpInfo(@javax.annotation.Nonnull SyncS3ScanRequest syncS3ScanRequest) throws ApiException {
        okhttp3.Call localVarCall = scanSyncS3PostValidateBeforeCall(syncS3ScanRequest, null);
        Type localVarReturnType = new TypeToken<ScanResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Download a file from S3, scan the file, and return the scan result. A bucket policy is required to grant attachmentAV access to the S3 objects.
     * @param syncS3ScanRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call scanSyncS3PostAsync(@javax.annotation.Nonnull SyncS3ScanRequest syncS3ScanRequest, final ApiCallback<ScanResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = scanSyncS3PostValidateBeforeCall(syncS3ScanRequest, _callback);
        Type localVarReturnType = new TypeToken<ScanResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for whoamiGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call whoamiGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/whoami";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKeyAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call whoamiGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return whoamiGetCall(_callback);

    }

    /**
     * 
     * Get information abour yourself.
     * @return Whoami
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public Whoami whoamiGet() throws ApiException {
        ApiResponse<Whoami> localVarResp = whoamiGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * 
     * Get information abour yourself.
     * @return ApiResponse&lt;Whoami&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Whoami> whoamiGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = whoamiGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Whoami>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Get information abour yourself.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call whoamiGetAsync(final ApiCallback<Whoami> _callback) throws ApiException {

        okhttp3.Call localVarCall = whoamiGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Whoami>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
