/*
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AsyncDownloadScanRequest
 */
public class AsyncDownloadScanRequestTest {
    private final AsyncDownloadScanRequest model = new AsyncDownloadScanRequest();

    /**
     * Model tests for AsyncDownloadScanRequest
     */
    @Test
    public void testAsyncDownloadScanRequest() {
        // TODO: test AsyncDownloadScanRequest
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'downloadHeaders'
     */
    @Test
    public void downloadHeadersTest() {
        // TODO: test downloadHeaders
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'callbackHeaders'
     */
    @Test
    public void callbackHeadersTest() {
        // TODO: test callbackHeaders
    }

    /**
     * Test the property 'traceId'
     */
    @Test
    public void traceIdTest() {
        // TODO: test traceId
    }

    /**
     * Test the property 'customData'
     */
    @Test
    public void customDataTest() {
        // TODO: test customData
    }

}
