/*
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.attachmentav.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SyncDownloadScanRequest
 */
public class SyncDownloadScanRequestTest {
    private final SyncDownloadScanRequest model = new SyncDownloadScanRequest();

    /**
     * Model tests for SyncDownloadScanRequest
     */
    @Test
    public void testSyncDownloadScanRequest() {
        // TODO: test SyncDownloadScanRequest
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'downloadHeaders'
     */
    @Test
    public void downloadHeadersTest() {
        // TODO: test downloadHeaders
    }

}
